# Generated by Django 3.2.2 on 2021-09-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend_list',
            unique_together={('friend', 'friend_relation')},
        ),
    ]
