# Generated by Django 3.2.2 on 2021-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='chat_img',
            field=models.FileField(blank=True, null=True, upload_to='chat_file/'),
        ),
    ]
