# Generated by Django 3.2.2 on 2021-09-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_chatmodel_chat_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='chat_line',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
