# Generated by Django 3.2.2 on 2021-09-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_chatmodel_chat_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chat_img_ext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
