# Generated by Django 3.2.2 on 2021-09-01 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chat_Time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
