# Generated by Django 3.2.2 on 2021-09-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatmodel_chat_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='chat_Time',
            new_name='chat_time',
        ),
    ]
