# Generated by Django 3.2.2 on 2021-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='Board_img',
            field=models.FileField(blank=True, null=True, upload_to='Board_img/'),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='Board_text',
            field=models.TextField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='Board_title',
            field=models.CharField(max_length=150),
        ),
    ]
