# Generated by Django 3.2.2 on 2021-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='Board_img',
            field=models.ImageField(blank=True, null=True, upload_to='Board_img/'),
        ),
    ]
