# Generated by Django 3.2.2 on 2021-09-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_boardmodel_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='Comment_Time',
            new_name='Board_Time',
        ),
    ]
