# Generated by Django 3.2.2 on 2021-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_rename_comment_time_boardmodel_board_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='Board_date',
            field=models.DateField(auto_now=True),
        ),
    ]
