# Generated by Django 3.2.2 on 2021-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_comment',
            name='Comment_Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
